### ISSUE TITLE
Лишний уровень абстракции

### ISSUE THREAD

**Issue by amarchenkov** [craftside/lunchvote#2]
https://github.com/craftside/lunchvote/blob/22ae53a9db094c0ad98e7adf92a268fd5a857642/src/main/java/ru/craftside/lunchvote/web/json/JacksonObjectMapper.java#L16

Избыточно создавать новый класс. Достаточно создать и сконфигурировать бин в контексте спринга

**Comment by craftside** [comment]
На текущей итерации контекст поднимается в xml, но в планах перевести конфиг в java-класс, и тогда этот класс туда мигрирует
