### ISSUE TITLE
Слишком много boilerplate кода

### ISSUE THREAD

**Issue by amarchenkov** [craftside/lunchvote#3]
https://github.com/craftside/lunchvote/blob/22ae53a9db094c0ad98e7adf92a268fd5a857642/src/main/java/ru/craftside/lunchvote/web/dto/RestaurantWithVoicesDto.java#L20

Конструкторы, геттеры и сеттеры занимают много места и делают код трудночитаемым. Можно использовать lombok чтобы упростить создание этого зоопарка

**Comment by craftside** [comment]
Ага 👍
