### ISSUE TITLE
Логгеры как правило делаю private и static

### ISSUE THREAD

**Issue by amarchenkov** [craftside/lunchvote#5]
https://github.com/craftside/lunchvote/blob/22ae53a9db094c0ad98e7adf92a268fd5a857642/src/main/java/ru/craftside/lunchvote/web/controller/MenuRestController.java#L28

**Comment by craftside** [comment]
Ок, возьму на вооружение. protected-логгер - для базового класса, здесь такое объявление сейчас неактуально
