### ISSUE TITLE
Много бесполезного логгирования

### ISSUE THREAD

**Issue by amarchenkov** [craftside/lunchvote#6]
https://github.com/craftside/lunchvote/blob/22ae53a9db094c0ad98e7adf92a268fd5a857642/src/main/java/ru/craftside/lunchvote/web/controller/RestaurantRestController.java#L70

Если оно тебе все же нужно, лучше вынести сего в отдельный аспект, предварительно подключив Spring-AOP

**Comment by craftside** [comment]
Спасибо за идею подступиться к AOP
PS Ну, здесь логгирование частично заменяет документирование методов (не полагаюсь на их именование)
