### ISSUE TITLE
Лишний класс

### ISSUE THREAD

**Issue by amarchenkov** [craftside/lunchvote#8]
https://github.com/craftside/lunchvote/blob/22ae53a9db094c0ad98e7adf92a268fd5a857642/src/main/java/ru/craftside/lunchvote/util/exception/ErrorType.java#L10

В проектированиее РЕСТ апи типы ошибок должны быть идентифицированы кодами HTTP. Введение своих кодов ошибок - плохая практика

**Comment by craftside** [comment]
Ок. Здесь идентифицируется в виде HttpStatus.UNPROCESSABLE_ENTITY, см. ExceptionInfoHandler, а ErrorType кастомизирует сообщение
