### ISSUE TITLE
ID сущности в equals and hashCode

### ISSUE THREAD

**Issue by amarchenkov** [craftside/lunchvote#9]
https://github.com/craftside/lunchvote/blob/22ae53a9db094c0ad98e7adf92a268fd5a857642/src/main/java/ru/craftside/lunchvote/model/AbstractBaseEntity.java#L45

Плохая практика использовать айдишник в equals и hashCode. Это генерируемое значение и может меняться. Например, при использованиее сущности в коллекциях - это может привести к трудноотлавливаем багам

**Comment by craftside** [comment]
В общем случае - плохо, согласен. Но здесь id гарантировано не меняется после инициализации
